{
  "constraints": {
    "MAX_DOESNT_WORK": 36,
    "MAX_WORKS": 16,
    "SUNDAYS": 52,
    "YEAR": 2026,
    "way/42506706": {
      "doesnt_work": [
        2,
        3,
        6,
        7,
        9,
        14,
        15,
        29,
        34,
        36,
        39,
        41,
        45,
        48,
        51
      ],
      "works": [
        1,
        17,
        47
      ]
    },
    "way/43624866": {
      "doesnt_work": [
        0,
        1,
        2,
        3,
        5,
        6,
        8,
        9,
        10,
        11,
        12,
        13,
        15,
        18,
        20,
        22,
        23,
        24,
        25,
        27,
        29,
        33,
        38,
        40,
        43,
        46,
        47,
        50
      ],
      "works": [
        14,
        26,
        34,
        41,
        44,
        45
      ]
    },
    "way/208244997": {
      "doesnt_work": [
        7,
        8,
        10,
        13,
        16,
        17,
        20,
        21,
        25,
        26,
        27,
        28,
        33,
        43
      ],
      "works": [
        2,
        4,
        12,
        23,
        36,
        39,
        40,
        42,
        45
      ]
    },
    "way/225198150": {
      "doesnt_work": [
        10,
        14,
        15,
        17,
        24,
        29,
        34,
        35,
        42,
        48
      ],
      "works": [
        38,
        40
      ]
    },
    "way/251043174": {
      "doesnt_work": [
        0,
        1,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        16,
        18,
        19,
        22,
        23,
        26,
        27,
        28,
        29,
        30,
        33,
        34,
        35,
        36,
        37,
        38,
        39,
        40,
        41,
        42,
        43,
        44,
        45,
        46,
        47,
        48
      ],
      "works": [
        2,
        3,
        4,
        13,
        14,
        17,
        20,
        25,
        49,
        51
      ]
    },
    "way/251043175": {
      "doesnt_work": [],
      "works": [
        7,
        10,
        18,
        21,
        27,
        29,
        41,
        49
      ]
    },
    "way/396026008": {
      "doesnt_work": [
        0,
        1,
        2,
        4,
        8,
        9,
        10,
        12,
        14,
        17,
        18,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        28,
        29,
        31,
        33,
        35,
        36,
        37,
        38,
        39,
        42,
        43,
        45,
        47,
        50
      ],
      "works": [
        6,
        11,
        19,
        32,
        40,
        46,
        48,
        51
      ]
    },
    "way/475108575": {
      "doesnt_work": [
        0,
        1,
        2,
        4,
        8,
        17,
        22,
        26,
        29,
        30,
        32,
        37,
        43,
        48,
        51
      ],
      "works": [
        7,
        12,
        13,
        19,
        23,
        25,
        27,
        28,
        33,
        34,
        38,
        39,
        41,
        42,
        44,
        46
      ]
    },
    "way/500404223": {
      "doesnt_work": [
        1,
        2,
        3,
        5,
        7,
        9,
        12,
        16,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
        33,
        35,
        37,
        38,
        39,
        41,
        43,
        44,
        45,
        46,
        47,
        48,
        49,
        50,
        51
      ],
      "works": [
        4,
        8,
        13,
        15,
        17,
        31,
        32,
        34,
        36,
        42
      ]
    },
    "way/512483210": {
      "doesnt_work": [],
      "works": [
        3,
        34,
        41
      ]
    },
    "way/562447775": {
      "doesnt_work": [
        0,
        3,
        10,
        13,
        25,
        26,
        27,
        31,
        32,
        43
      ],
      "works": [
        15,
        48
      ]
    },
    "way/576662466": {
      "doesnt_work": [
        1,
        2,
        3,
        5,
        6,
        7,
        9,
        10,
        12,
        13,
        16,
        19,
        20,
        21,
        22,
        23,
        24,
        26,
        30,
        31,
        33,
        34,
        36,
        37,
        38,
        40,
        41,
        43,
        45,
        47,
        48
      ],
      "works": [
        18,
        27,
        29,
        35,
        42,
        44,
        50,
        51
      ]
    },
    "way/666636696": {
      "doesnt_work": [
        1,
        2,
        3,
        5,
        6,
        7,
        9,
        10,
        11,
        12,
        17,
        18,
        21,
        22,
        24,
        26,
        28,
        30,
        32,
        34,
        35,
        37,
        38,
        39,
        40,
        43,
        44,
        47,
        48
      ],
      "works": [
        0,
        4,
        8,
        13,
        15,
        16,
        19,
        20,
        25,
        29,
        41,
        42,
        45,
        46,
        50,
        51
      ]
    },
    "node/697903423": {
      "doesnt_work": [
        0,
        1,
        2,
        3,
        4,
        5,
        8,
        10,
        11,
        14,
        18,
        19,
        20,
        24,
        25,
        26,
        27,
        29,
        30,
        31,
        33,
        34,
        35,
        37,
        41,
        42,
        44,
        46,
        47,
        49,
        51
      ],
      "works": [
        13,
        16,
        21,
        32,
        38,
        40,
        43,
        45,
        50
      ]
    },
    "node/697903545": {
      "doesnt_work": [
        1,
        12,
        14,
        19,
        27,
        32,
        46,
        47,
        51
      ],
      "works": [
        2,
        6,
        13,
        15,
        22,
        26,
        35,
        42,
        43,
        49,
        50
      ]
    },
    "way/732434988": {
      "doesnt_work": [
        1,
        5,
        16,
        18,
        21,
        23,
        26,
        27,
        31,
        35,
        40,
        47
      ],
      "works": [
        2,
        6,
        10,
        14,
        24,
        30,
        44,
        50
      ]
    },
    "way/1159151706": {
      "doesnt_work": [
        2,
        3,
        8,
        9,
        10,
        23,
        26,
        28,
        30,
        35,
        36,
        42,
        47,
        48,
        49,
        50
      ],
      "works": [
        1,
        7,
        11,
        16,
        21,
        25,
        32,
        34,
        37,
        41,
        43
      ]
    },
    "way/1181759148": {
      "doesnt_work": [
        24,
        25,
        26,
        32,
        35,
        44,
        51
      ],
      "works": [
        0,
        4,
        12,
        20,
        21,
        23,
        27,
        33,
        34,
        39,
        42,
        43,
        46
      ]
    },
    "way/1292202147": {
      "doesnt_work": [
        0,
        14,
        19,
        20,
        28,
        30,
        38,
        39,
        40,
        43,
        49
      ],
      "works": [
        12,
        24,
        26,
        42
      ]
    },
    "way/1293720412": {
      "doesnt_work": [
        1,
        2,
        6,
        8,
        11,
        15,
        17,
        18,
        22,
        24,
        27,
        38,
        39,
        41,
        44,
        45,
        48,
        49
      ],
      "works": [
        5,
        10,
        13,
        28,
        29,
        30,
        32,
        42,
        43,
        50
      ]
    },
    "way/1293731255": {
      "doesnt_work": [
        4,
        5,
        7,
        10,
        14,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        26,
        28,
        29,
        32,
        33,
        34,
        37,
        38,
        39,
        42,
        43,
        46,
        48,
        49,
        51
      ],
      "works": [
        0,
        6,
        9,
        12,
        15,
        24,
        25,
        31,
        36,
        40,
        41,
        44,
        45
      ]
    },
    "way/1293972970": {
      "doesnt_work": [
        2,
        4,
        5,
        6,
        8,
        9,
        14,
        16,
        19,
        20,
        22,
        23,
        24,
        26,
        30,
        38,
        42
      ],
      "works": [
        15,
        17,
        31,
        33,
        40,
        49,
        51
      ]
    },
    "way/1294485907": {
      "doesnt_work": [
        0,
        2,
        4,
        6,
        7,
        8,
        9,
        10,
        12,
        14,
        15,
        16,
        17,
        18,
        20,
        22,
        23,
        27,
        28,
        31,
        32,
        33,
        35,
        41,
        42,
        44,
        45,
        46,
        49,
        50
      ],
      "works": [
        1,
        3,
        13,
        21,
        24,
        26,
        29,
        34,
        36,
        37,
        43,
        47,
        51
      ]
    },
    "way/1294841394": {
      "doesnt_work": [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        13,
        14,
        15,
        17,
        18,
        20,
        21,
        22,
        23,
        25,
        27,
        30,
        31,
        35,
        40,
        44,
        51
      ],
      "works": [
        16
      ]
    },
    "way/1304298007": {
      "doesnt_work": [
        11,
        14,
        18,
        25,
        32,
        39,
        48
      ],
      "works": [
        8,
        15,
        30,
        42
      ]
    },
    "way/1307016751": {
      "doesnt_work": [
        1,
        21,
        26,
        38,
        39,
        45
      ],
      "works": [
        10,
        19,
        49
      ]
    },
    "way/1332425643": {
      "doesnt_work": [
        28,
        46
      ],
      "works": [
        4,
        6,
        7,
        12,
        15,
        19,
        36,
        37,
        38,
        40,
        44,
        45
      ]
    },
    "node/1456728213": {
      "doesnt_work": [
        14,
        20,
        36,
        37,
        39,
        40,
        45,
        46,
        51
      ],
      "works": [
        0,
        4,
        6,
        21,
        23,
        26,
        27,
        29,
        31,
        32,
        41,
        42,
        50
      ]
    },
    "node/1709227845": {
      "doesnt_work": [
        0,
        1,
        2,
        7,
        8,
        12,
        14,
        18,
        19,
        21,
        24,
        25,
        26,
        27,
        30,
        33,
        38,
        39,
        40,
        42,
        44,
        47,
        48,
        51
      ],
      "works": [
        5,
        15,
        17,
        20,
        28,
        29,
        36,
        50
      ]
    },
    "node/1734409432": {
      "doesnt_work": [
        4,
        7,
        8,
        9,
        10,
        11,
        12,
        21,
        22,
        24,
        29,
        31,
        32,
        34,
        38,
        40,
        42,
        43,
        45,
        46,
        49,
        51
      ],
      "works": [
        1,
        5,
        14,
        15,
        18,
        19,
        23,
        25,
        28,
        30,
        33,
        35,
        37,
        44,
        50
      ]
    },
    "node/1739121436": {
      "doesnt_work": [
        0,
        1,
        2,
        3,
        5,
        6,
        8,
        10,
        11,
        16,
        20,
        21,
        22,
        33,
        34,
        35,
        37,
        38,
        40,
        41,
        46,
        48,
        49
      ],
      "works": [
        12,
        14,
        18
      ]
    },
    "node/2290604109": {
      "doesnt_work": [
        21,
        33,
        35,
        38,
        39,
        47,
        49
      ],
      "works": [
        3,
        4,
        5,
        7,
        9,
        15,
        19,
        25,
        31,
        36,
        40,
        42,
        43,
        46,
        50
      ]
    },
    "node/3849995968": {
      "doesnt_work": [
        0,
        7,
        14,
        15,
        20,
        21,
        25,
        29,
        33,
        48
      ],
      "works": [
        3,
        5,
        6,
        13,
        16,
        19,
        27,
        36,
        37,
        39,
        40,
        42,
        46,
        51
      ]
    },
    "node/4365440790": {
      "doesnt_work": [
        1,
        6,
        11,
        20,
        23,
        46,
        50
      ],
      "works": [
        2,
        4,
        12,
        14,
        16,
        18,
        27,
        29,
        37,
        40,
        44,
        45,
        48,
        49,
        51
      ]
    },
    "node/4402119093": {
      "doesnt_work": [
        1,
        2,
        5,
        7,
        16,
        17,
        20,
        21,
        26,
        28,
        29,
        30,
        32,
        33,
        35,
        37,
        49,
        51
      ],
      "works": [
        19,
        36,
        38,
        47,
        50
      ]
    },
    "node/4402166889": {
      "doesnt_work": [
        2,
        5,
        11,
        17,
        22,
        27,
        28,
        30,
        31,
        33,
        36,
        37,
        41,
        46,
        47,
        48,
        49
      ],
      "works": []
    },
    "node/6653414472": {
      "doesnt_work": [
        0,
        1,
        5,
        7,
        8,
        9,
        11,
        14,
        15,
        16,
        17,
        19,
        22,
        23,
        27,
        28,
        29,
        30,
        33,
        34,
        37,
        39,
        40,
        43,
        45,
        46,
        47,
        48,
        49
      ],
      "works": [
        2,
        6,
        10,
        18,
        20,
        21,
        25,
        26,
        31,
        35,
        42,
        44,
        51
      ]
    },
    "node/6653448885": {
      "doesnt_work": [
        0,
        6,
        8,
        10,
        11,
        15,
        19,
        20,
        27,
        30,
        32,
        36,
        42,
        48,
        51
      ],
      "works": [
        1,
        38,
        40
      ]
    },
    "node/6715741845": {
      "doesnt_work": [
        0,
        3,
        5,
        6,
        13,
        14,
        16,
        18,
        20,
        21,
        22,
        23,
        25,
        27,
        28,
        31,
        33,
        34,
        36,
        37,
        39,
        40,
        44,
        46,
        47,
        51
      ],
      "works": [
        4,
        8,
        9,
        12,
        15,
        17,
        24,
        26,
        29,
        30,
        32,
        35,
        38,
        45,
        48,
        50
      ]
    },
    "node/6765147079": {
      "doesnt_work": [
        0,
        3,
        5,
        7,
        8,
        10,
        12,
        13,
        15,
        16,
        18,
        19,
        21,
        23,
        25,
        27,
        28,
        29,
        31,
        33,
        34,
        35,
        36,
        37,
        38,
        39,
        46,
        47,
        48,
        50,
        51
      ],
      "works": [
        2,
        9,
        14,
        20,
        24,
        26,
        30,
        41,
        42,
        44,
        45,
        49
      ]
    },
    "node/6823761120": {
      "doesnt_work": [
        1,
        2,
        3,
        5,
        6,
        10,
        14,
        19,
        20,
        21,
        23,
        24,
        28,
        29,
        42,
        47,
        48,
        49
      ],
      "works": [
        15,
        40
      ]
    },
    "node/6896523244": {
      "doesnt_work": [
        5,
        9,
        10,
        11,
        14,
        16,
        25,
        34,
        41,
        43,
        48
      ],
      "works": [
        15,
        26,
        33,
        36
      ]
    },
    "node/7536532722": {
      "doesnt_work": [
        1,
        5,
        9,
        11,
        12,
        14,
        15,
        21,
        24,
        25,
        30,
        32,
        36,
        37,
        38,
        39,
        44,
        45,
        51
      ],
      "works": [
        0,
        4,
        10,
        16,
        18,
        22,
        28,
        29,
        34,
        40,
        42,
        43,
        49,
        50
      ]
    },
    "node/9267193443": {
      "doesnt_work": [
        2,
        3,
        4,
        5,
        6,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        16,
        17,
        18,
        19,
        22,
        23,
        28,
        29,
        30,
        31,
        32,
        35,
        36,
        37,
        38,
        40,
        43,
        44,
        45,
        46,
        47,
        49,
        50,
        51
      ],
      "works": []
    },
    "node/9392589356": {
      "doesnt_work": [
        0,
        4,
        5,
        7,
        8,
        9,
        14,
        17,
        20,
        23,
        25,
        27,
        32,
        33,
        34,
        37,
        38,
        42,
        44,
        49,
        50
      ],
      "works": [
        16,
        18,
        30,
        47,
        51
      ]
    },
    "node/9804228487": {
      "doesnt_work": [
        9,
        24,
        32,
        36
      ],
      "works": [
        1,
        6,
        14,
        20,
        23,
        30,
        35,
        39,
        40,
        43,
        44,
        47
      ]
    },
    "node/9837851184": {
      "doesnt_work": [
        10,
        17,
        26,
        27,
        33,
        38
      ],
      "works": [
        2,
        7,
        19,
        31
      ]
    },
    "node/10779670469": {
      "doesnt_work": [
        4,
        8,
        11,
        15,
        19,
        28,
        29,
        33,
        35,
        40,
        44,
        45,
        51
      ],
      "works": [
        2,
        6,
        9,
        17,
        23,
        26,
        31,
        37,
        39,
        41,
        46,
        47,
        50
      ]
    },
    "node/11775261106": {
      "doesnt_work": [
        0,
        2,
        6,
        7,
        9,
        10,
        11,
        12,
        14,
        16,
        17,
        18,
        19,
        20,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
        31,
        33,
        34,
        35,
        37,
        39,
        44,
        45,
        46,
        47,
        48,
        51
      ],
      "works": [
        1,
        3,
        4,
        5,
        8,
        13,
        15,
        21,
        36,
        38,
        40,
        41,
        42,
        49
      ]
    },
    "node/11775268935": {
      "doesnt_work": [
        4,
        5,
        7,
        8,
        9,
        11,
        12,
        13,
        15,
        16,
        17,
        18,
        21,
        22,
        23,
        24,
        26,
        27,
        28,
        34,
        36,
        37,
        38,
        44,
        45,
        48,
        50
      ],
      "works": [
        1,
        2,
        3,
        14,
        19,
        25,
        29,
        30,
        32,
        33,
        39,
        41,
        42,
        46
      ]
    },
    "node/11775286978": {
      "doesnt_work": [
        1,
        4,
        5,
        6,
        9,
        11,
        17,
        18,
        19,
        22,
        24,
        25,
        31,
        32,
        33,
        36,
        38,
        40,
        41,
        42,
        43,
        45,
        48,
        49,
        50
      ],
      "works": [
        14,
        21,
        26,
        27,
        28,
        29
      ]
    },
    "node/11775288369": {
      "doesnt_work": [
        8,
        9,
        10,
        11,
        15,
        16,
        21,
        23,
        24,
        25,
        28,
        29,
        30,
        31,
        32,
        37,
        39,
        40,
        45,
        47,
        48,
        50
      ],
      "works": [
        3,
        7,
        18,
        19,
        22,
        26,
        27,
        38,
        42,
        51
      ]
    },
    "node/11779004820": {
      "doesnt_work": [
        0,
        1,
        4,
        5,
        9,
        11,
        17,
        19,
        21,
        22,
        25,
        33,
        36,
        42,
        44,
        50,
        51
      ],
      "works": []
    },
    "node/11779489591": {
      "doesnt_work": [
        3,
        5,
        6,
        8,
        9,
        11,
        17,
        18,
        22,
        30,
        32,
        33,
        34,
        37,
        41,
        42,
        44,
        47,
        48
      ],
      "works": [
        10,
        21,
        23,
        24,
        26,
        29
      ]
    },
    "node/11779490406": {
      "doesnt_work": [
        0,
        2,
        3,
        9,
        14,
        15,
        17,
        20,
        28,
        34,
        36,
        38,
        40,
        41,
        45,
        46,
        50,
        51
      ],
      "works": [
        7,
        22,
        27
      ]
    },
    "node/11779512696": {
      "doesnt_work": [
        1,
        2,
        3,
        4,
        5,
        6,
        9,
        13,
        14,
        15,
        16,
        17,
        18,
        22,
        23,
        26,
        29,
        30,
        32,
        33,
        34,
        35,
        37,
        38,
        39,
        40,
        41,
        42,
        43,
        44,
        46,
        48,
        49,
        51
      ],
      "works": [
        0,
        7,
        8,
        11,
        20,
        24,
        27,
        31,
        47
      ]
    },
    "node/12085232210": {
      "doesnt_work": [
        12,
        16,
        20,
        29,
        42,
        43,
        48
      ],
      "works": [
        4,
        5,
        10,
        14,
        19,
        21,
        25,
        32,
        33,
        40,
        46,
        47
      ]
    },
    "node/12147658121": {
      "doesnt_work": [
        4,
        10,
        13,
        31,
        32,
        34,
        39,
        40,
        41,
        43,
        44
      ],
      "works": [
        9,
        12,
        16
      ]
    },
    "node/12316085415": {
      "doesnt_work": [
        5,
        27,
        39
      ],
      "works": [
        4,
        9,
        17,
        19,
        20,
        28,
        30,
        40,
        48,
        51
      ]
    },
    "node/12372532427": {
      "doesnt_work": [
        1,
        6,
        7,
        8,
        9,
        10,
        11,
        13,
        14,
        16,
        19,
        20,
        21,
        22,
        26,
        27,
        30,
        32,
        33,
        36,
        37,
        38,
        40,
        42,
        43,
        44,
        45,
        46,
        47,
        49,
        50,
        51
      ],
      "works": [
        2,
        3,
        4,
        5,
        18,
        23,
        28,
        29,
        41
      ]
    },
    "node/12372535038": {
      "doesnt_work": [
        2,
        7,
        8,
        12,
        13,
        15,
        19,
        20,
        23,
        25,
        26,
        27,
        30,
        36,
        39,
        42,
        45,
        48
      ],
      "works": [
        3,
        4,
        6,
        21,
        24,
        35,
        38,
        40,
        41,
        43,
        44,
        49,
        50
      ]
    },
    "node/12410057078": {
      "doesnt_work": [
        3,
        6,
        9,
        17,
        29,
        34,
        37,
        43,
        48
      ],
      "works": [
        1,
        5,
        8,
        11,
        12,
        13,
        14,
        19,
        21,
        23,
        27,
        31,
        32,
        41,
        42,
        46
      ]
    },
    "node/12412755421": {
      "doesnt_work": [
        2,
        12,
        17,
        20,
        26,
        29,
        31,
        43,
        48,
        50,
        51
      ],
      "works": [
        9,
        10,
        24,
        38
      ]
    },
    "node/12453191584": {
      "doesnt_work": [
        0,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        13,
        14,
        16,
        17,
        18,
        20,
        21,
        26,
        27,
        28,
        31,
        32,
        33,
        35,
        36,
        37,
        38,
        39,
        40,
        41,
        45,
        46,
        47,
        50,
        51
      ],
      "works": [
        12,
        15,
        19,
        23,
        30,
        34,
        43
      ]
    },
    "node/12495479022": {
      "doesnt_work": [
        0,
        3,
        8,
        11,
        27,
        38,
        40,
        47,
        51
      ],
      "works": [
        1,
        5,
        6,
        14,
        15,
        20,
        21,
        23,
        24,
        32,
        41,
        50
      ]
    },
    "node/12538802906": {
      "doesnt_work": [
        3,
        7,
        9,
        13,
        15,
        18,
        19,
        26,
        27,
        29,
        33,
        35,
        38,
        42,
        44,
        46
      ],
      "works": []
    },
    "node/12538825424": {
      "doesnt_work": [
        0,
        1,
        4,
        5,
        9,
        10,
        12,
        13,
        16,
        17,
        18,
        19,
        23,
        24,
        26,
        27,
        28,
        29,
        30,
        32,
        34,
        35,
        37,
        38,
        40,
        41,
        42,
        43,
        44,
        47,
        48,
        49,
        50,
        51
      ],
      "works": [
        7,
        31
      ]
    },
    "node/12538931824": {
      "doesnt_work": [
        28,
        43
      ],
      "works": [
        4,
        6,
        8,
        15,
        21,
        22,
        37,
        40,
        42,
        46,
        50
      ]
    },
    "node/12657258756": {
      "doesnt_work": [
        2,
        14,
        20,
        33
      ],
      "works": [
        8,
        11,
        29,
        30,
        40,
        41,
        43,
        44,
        49,
        50
      ]
    },
    "node/12657258808": {
      "doesnt_work": [
        2,
        12,
        16,
        18,
        19,
        20,
        25,
        30,
        32,
        34,
        41,
        51
      ],
      "works": [
        50
      ]
    },
    "node/12657258819": {
      "doesnt_work": [
        2,
        4,
        6,
        11,
        12,
        13,
        20,
        26,
        30,
        32,
        34,
        35,
        36,
        38,
        40,
        42,
        43,
        44,
        45,
        46,
        50
      ],
      "works": [
        3,
        7,
        17,
        21,
        23,
        24,
        25,
        27,
        28,
        41,
        49
      ]
    }
  },
  "created_at": "2026-06-17T14:11:11.046975+00:00",
  "data": {
    "way/42506706": {
      "name": "Plodine",
      "brand": "Plodine",
      "rating": 4.1,
      "user_ratings_total": 1110,
      "formatted_address": "Ul. kralja Tomislava 51, 48260, Križevci, Croatia",
      "coordinates": [
        16.5463641,
        46.0143463
      ],
      "value_for_radius": 1110.0,
      "radius_km": 2.7268
    },
    "way/43624866": {
      "name": "Lidl",
      "brand": "Lidl",
      "rating": 4.4,
      "user_ratings_total": 965,
      "formatted_address": "Ul. Nikole Tesle 2, 48260, Križevci, Croatia",
      "coordinates": [
        16.536868,
        46.0210986
      ],
      "value_for_radius": 965.0,
      "radius_km": 2.6835
    },
    "way/208244997": {
      "name": "Intersport Križevci 1",
      "brand": "",
      "rating": 4.4,
      "user_ratings_total": 148,
      "formatted_address": "Ul. Petra Zrinskog 8, 48260, Križevci, Croatia",
      "coordinates": [
        16.5483929,
        46.0220604
      ],
      "value_for_radius": 148.0,
      "radius_km": 0.6493
    },
    "way/225198150": {
      "name": "Robin Market 37",
      "brand": "",
      "rating": 4.6,
      "user_ratings_total": 162,
      "formatted_address": "Ul. Braće Radić 6, 48000, Koprivnica, Croatia",
      "coordinates": [
        16.8390733,
        46.1616584
      ],
      "value_for_radius": 162.0,
      "radius_km": 1.0469
    },
    "way/251043174": {
      "name": "KTC Restoran 'Ivana'",
      "brand": "",
      "rating": 4.2,
      "user_ratings_total": 316,
      "formatted_address": "Ul. Ivana Česmičkog 15/3, 48000, Koprivnica, Croatia",
      "coordinates": [
        16.8355222,
        46.1806185
      ],
      "value_for_radius": 316.0,
      "radius_km": 1.3739
    },
    "way/251043175": {
      "name": "Plodine",
      "brand": "Plodine",
      "rating": 3.9,
      "user_ratings_total": 1038,
      "formatted_address": "Ul. Ivana Česmičkog 5a, 48000, Koprivnica, Croatia",
      "coordinates": [
        16.8386125,
        46.182885
      ],
      "value_for_radius": 1038.0,
      "radius_km": 2.9943
    },
    "way/396026008": {
      "name": "Lidl",
      "brand": "Lidl",
      "rating": 4.5,
      "user_ratings_total": 1473,
      "formatted_address": "Ul. Grada Vukovara 11, 48350, Đurđevac, Croatia",
      "coordinates": [
        17.0649138,
        46.0308482
      ],
      "value_for_radius": 1473.0,
      "radius_km": 3.9552
    },
    "way/475108575": {
      "name": "KTC Robni centar Križevci",
      "brand": "",
      "rating": 4.6,
      "user_ratings_total": 586,
      "formatted_address": "Ul. Nikole Tesle 18, 48260, Križevci, Croatia",
      "coordinates": [
        16.5365302,
        46.0157637
      ],
      "value_for_radius": 586.0,
      "radius_km": 2.0715
    },
    "way/500404223": {
      "name": "Konzum",
      "brand": "Konzum",
      "rating": 3.9,
      "user_ratings_total": 421,
      "formatted_address": "Ul. Vladimira Nazora 5, 48350, Đurđevac, Croatia",
      "coordinates": [
        17.0667141,
        46.0394805
      ],
      "value_for_radius": 421.0,
      "radius_km": 1.8878
    },
    "way/512483210": {
      "name": "Lidl",
      "brand": "Lidl",
      "rating": 4.5,
      "user_ratings_total": 1752,
      "formatted_address": "Križevačka ul. 21, 48000, Koprivnica, Croatia",
      "coordinates": [
        16.8247641,
        46.1593788
      ],
      "value_for_radius": 1752.0,
      "radius_km": 3.5966
    },
    "way/562447775": {
      "name": "SPAR supermarket Koprivnica Kolodvorska",
      "brand": "Spar",
      "rating": 4.2,
      "user_ratings_total": 607,
      "formatted_address": "Kolodvorska ul. 31a, 48000, Koprivnica, Croatia",
      "coordinates": [
        16.8173966,
        46.1636138
      ],
      "value_for_radius": 607.0,
      "radius_km": 2.064
    },
    "way/576662466": {
      "name": "Kaufland Koprivnica",
      "brand": "Kaufland",
      "rating": 4.3,
      "user_ratings_total": 1627,
      "formatted_address": "Ul. Ivana Česmičkog 26, 48000, Koprivnica, Croatia",
      "coordinates": [
        16.8192322,
        46.1717299
      ],
      "value_for_radius": 1627.0,
      "radius_km": 3.8401
    },
    "way/666636696": {
      "name": "Sloga - Podravska trgovina P-923",
      "brand": "",
      "rating": 4.4,
      "user_ratings_total": 27,
      "formatted_address": "Ul. bana Josipa Jelačića 95, 48323, Hlebine, Croatia",
      "coordinates": [
        16.9665664,
        46.1534122
      ],
      "value_for_radius": 27.0,
      "radius_km": 0.5476
    },
    "node/697903423": {
      "name": "Robin Market 11",
      "brand": "",
      "rating": 4.8,
      "user_ratings_total": 63,
      "formatted_address": "Ul. Franje Račkog 33, 48260, Križevci, Croatia",
      "coordinates": [
        16.5424267,
        46.0314499
      ],
      "value_for_radius": 63.0,
      "radius_km": 0.7329
    },
    "node/697903545": {
      "name": "PPK Bjelovar",
      "brand": "",
      "rating": 3.9,
      "user_ratings_total": 15,
      "formatted_address": "Ul. Franje Markovića 85, 48260, Križevci, Croatia",
      "coordinates": [
        16.5394059,
        46.0386176
      ],
      "value_for_radius": 15.0,
      "radius_km": 0.5
    },
    "way/732434988": {
      "name": "SPAR supermarket Križevci",
      "brand": "Spar",
      "rating": 4.4,
      "user_ratings_total": 358,
      "formatted_address": "Ul. Tadije Smičiklasa 5a, 48260, Križevci, Croatia",
      "coordinates": [
        16.5416369,
        46.0272044
      ],
      "value_for_radius": 358.0,
      "radius_km": 1.6312
    },
    "way/1159151706": {
      "name": "Eurospin Križevci",
      "brand": "",
      "rating": 4.3,
      "user_ratings_total": 460,
      "formatted_address": "Ul. kralja Tomislava 47a, 48260, Križevci, Croatia",
      "coordinates": [
        16.5472724,
        46.0171266
      ],
      "value_for_radius": 460.0,
      "radius_km": 1.4187
    },
    "way/1181759148": {
      "name": "Studenac Market",
      "brand": "Studenac",
      "rating": 4.3,
      "user_ratings_total": 10,
      "formatted_address": "Trg Stjepana Radića 3, 48350, Virje, Croatia",
      "coordinates": [
        16.9894911,
        46.0689033
      ],
      "value_for_radius": 10.0,
      "radius_km": 0.5
    },
    "way/1292202147": {
      "name": "NTL TRGOVINA BR. 2088",
      "brand": "",
      "rating": 4.2,
      "user_ratings_total": 115,
      "formatted_address": "Ul. Pavla Kvakana 1, 48316, Đelekovec, Croatia",
      "coordinates": [
        16.8621117,
        46.2492227
      ],
      "value_for_radius": 115.0,
      "radius_km": 0.6876
    },
    "way/1293720412": {
      "name": "Robin Market 50",
      "brand": "",
      "rating": 4.8,
      "user_ratings_total": 35,
      "formatted_address": "Ul. Pavla Kvakana 8, 48316, Đelekovec, Croatia",
      "coordinates": [
        16.8613347,
        46.2491795
      ],
      "value_for_radius": 35.0,
      "radius_km": 0.5
    },
    "way/1293731255": {
      "name": "NTL TRGOVINA BR. 4106",
      "brand": "",
      "rating": 4.1,
      "user_ratings_total": 27,
      "formatted_address": "Štaglinec 38C, 48000, Koprivnica, Croatia",
      "coordinates": [
        16.865119,
        46.1325092
      ],
      "value_for_radius": 27.0,
      "radius_km": 0.5385
    },
    "way/1293972970": {
      "name": "Robin Market 50",
      "brand": "",
      "rating": 4.8,
      "user_ratings_total": 35,
      "formatted_address": "Ul. Pavla Kvakana 8, 48316, Đelekovec, Croatia",
      "coordinates": [
        16.8614483,
        46.2495842
      ],
      "value_for_radius": 35.0,
      "radius_km": 0.5
    },
    "way/1294485907": {
      "name": "Studenac Market",
      "brand": "Studenac",
      "rating": 4.7,
      "user_ratings_total": 7,
      "formatted_address": "Koprivnička ul. 38, 48350, Novigrad Podravski, Croatia",
      "coordinates": [
        16.9523676,
        46.0803494
      ],
      "value_for_radius": 7.0,
      "radius_km": 0.5
    },
    "way/1294841394": {
      "name": "Dergez trgovina",
      "brand": "",
      "rating": 4.8,
      "user_ratings_total": 8,
      "formatted_address": "Štaglinec 66G, 48000, Koprivnica, Croatia",
      "coordinates": [
        16.8721783,
        46.124554
      ],
      "value_for_radius": 8.0,
      "radius_km": 0.5
    },
    "way/1304298007": {
      "name": "Eurospin Koprivnica",
      "brand": "",
      "rating": 4.3,
      "user_ratings_total": 220,
      "formatted_address": "Ulica Mihovila P. Miškine 5, 48000, Koprivnica, Croatia",
      "coordinates": [
        16.8323427,
        46.165345
      ],
      "value_for_radius": 220.0,
      "radius_km": 1.0861
    },
    "way/1307016751": {
      "name": "KTC Robni centar Đurđevac",
      "brand": "",
      "rating": 4.4,
      "user_ratings_total": 395,
      "formatted_address": "Ul. Đure Basaričeka 16, 48350, Đurđevac, Croatia",
      "coordinates": [
        17.0645096,
        46.0426458
      ],
      "value_for_radius": 395.0,
      "radius_km": 1.86
    },
    "way/1332425643": {
      "name": "Shopping center Konzum Koprivnica",
      "brand": "Konzum",
      "rating": 4.2,
      "user_ratings_total": 634,
      "formatted_address": "Ul. kneza Domagoja 5, 48000, Koprivnica, Croatia",
      "coordinates": [
        16.8364995,
        46.1647655
      ],
      "value_for_radius": 634.0,
      "radius_km": 2.1238
    },
    "node/1456728213": {
      "name": "KTC City Cafe",
      "brand": "",
      "rating": 4.3,
      "user_ratings_total": 1049,
      "formatted_address": "Trg Svetog Florijana 1/3, 48260, Križevci, Croatia",
      "coordinates": [
        16.5456302,
        46.022553
      ],
      "value_for_radius": 1049.0,
      "radius_km": 2.5345
    },
    "node/1709227845": {
      "name": "KITRO trgovina TP 86",
      "brand": "",
      "rating": 4.1,
      "user_ratings_total": 60,
      "formatted_address": "D41 72, 48322, Drnje, Croatia",
      "coordinates": [
        16.9089868,
        46.2074315
      ],
      "value_for_radius": 60.0,
      "radius_km": 0.8149
    },
    "node/1734409432": {
      "name": "Robin Market 27",
      "brand": "",
      "rating": 5,
      "user_ratings_total": 15,
      "formatted_address": "48267, Vukovec, Croatia",
      "coordinates": [
        16.4196776,
        46.1066928
      ],
      "value_for_radius": 15.0,
      "radius_km": 0.5
    },
    "node/1739121436": {
      "name": "Studenac Market",
      "brand": "",
      "rating": 3.8,
      "user_ratings_total": 6,
      "formatted_address": "Podravska ul. 111, 48316, Torčec, Croatia",
      "coordinates": [
        16.8837823,
        46.2211504
      ],
      "value_for_radius": 6.0,
      "radius_km": 0.5
    },
    "node/2290604109": {
      "name": "Jelena trade",
      "brand": "",
      "rating": 3.1,
      "user_ratings_total": 19,
      "formatted_address": "Varaždinska cesta 81, 48311, Kunovec Breg, Croatia",
      "coordinates": [
        16.7651847,
        46.1856225
      ],
      "value_for_radius": 19.0,
      "radius_km": 0.5
    },
    "node/3849995968": {
      "name": "Studenac Market",
      "brand": "Studenac",
      "rating": 4.3,
      "user_ratings_total": 3,
      "formatted_address": "Ul. bana Josipa Jelačića 95, 48316, Hlebine, Croatia",
      "coordinates": [
        16.9631104,
        46.156099
      ],
      "value_for_radius": 3.0,
      "radius_km": 0.5
    },
    "node/4365440790": {
      "name": "Studenac Market",
      "brand": "",
      "rating": 4.7,
      "user_ratings_total": 3,
      "formatted_address": "Ul. Novi Brežanec 6, 48000, Koprivnica, Croatia",
      "coordinates": [
        16.8311025,
        46.1560022
      ],
      "value_for_radius": 3.0,
      "radius_km": 0.5
    },
    "node/4402119093": {
      "name": "Offertissima",
      "brand": "",
      "rating": 4.5,
      "user_ratings_total": 383,
      "formatted_address": "Ul. Josipa Vargovića 2, 48000, Koprivnica, Croatia",
      "coordinates": [
        16.8259802,
        46.1630704
      ],
      "value_for_radius": 383.0,
      "radius_km": 1.1353
    },
    "node/4402166889": {
      "name": "Konzum",
      "brand": "Konzum",
      "rating": 3.6,
      "user_ratings_total": 53,
      "formatted_address": "Ulica hrvatske državnosti 12, 48000, Koprivnica, Croatia",
      "coordinates": [
        16.8266779,
        46.1625023
      ],
      "value_for_radius": 53.0,
      "radius_km": 0.5
    },
    "node/6653414472": {
      "name": "NTL TRGOVINA BR. 4110",
      "brand": "",
      "rating": 4.9,
      "user_ratings_total": 8,
      "formatted_address": "Kuzminec 110, 48312, Rasinja, Croatia",
      "coordinates": [
        16.7578204,
        46.2380386
      ],
      "value_for_radius": 8.0,
      "radius_km": 0.5
    },
    "node/6653448885": {
      "name": "NTL trgovina br. 118",
      "brand": "",
      "rating": 3.5,
      "user_ratings_total": 1,
      "formatted_address": "Ulica Matije Gupca 4, 48314, Koprivnički Ivanec, Croatia",
      "coordinates": [
        16.8147643,
        46.2021972
      ],
      "value_for_radius": 1.0,
      "radius_km": 0.5
    },
    "node/6715741845": {
      "name": "Market Dergez",
      "brand": "",
      "rating": 4.2,
      "user_ratings_total": 9,
      "formatted_address": "Kralja Tomislava 5, 48324, Koprivnički Bregi, Croatia",
      "coordinates": [
        16.9008631,
        46.1332117
      ],
      "value_for_radius": 9.0,
      "radius_km": 0.5
    },
    "node/6765147079": {
      "name": "NTL trgovina br. 118",
      "brand": "",
      "rating": 3.5,
      "user_ratings_total": 1,
      "formatted_address": "Ulica Matije Gupca 4, 48314, Koprivnički Ivanec, Croatia",
      "coordinates": [
        16.8176946,
        46.1978827
      ],
      "value_for_radius": 1.0,
      "radius_km": 0.5
    },
    "node/6823761120": {
      "name": "Studenac Market",
      "brand": "",
      "rating": 3.5,
      "user_ratings_total": 1,
      "formatted_address": "Repaš 63, 48350, Repaš, Croatia",
      "coordinates": [
        17.0832936,
        46.1458772
      ],
      "value_for_radius": 1.0,
      "radius_km": 0.5
    },
    "node/6896523244": {
      "name": "Robin Market 36",
      "brand": "",
      "rating": 4.2,
      "user_ratings_total": 5,
      "formatted_address": "Ul. Matije Gupca 40, 48260, Križevci, Croatia",
      "coordinates": [
        16.5468056,
        46.0220176
      ],
      "value_for_radius": 5.0,
      "radius_km": 0.5
    },
    "node/7536532722": {
      "name": "NTL",
      "brand": "",
      "rating": 4.7,
      "user_ratings_total": 33,
      "formatted_address": "Ul. kralja Tomislava 5, 48317, Legrad, Croatia",
      "coordinates": [
        16.8532912,
        46.2961155
      ],
      "value_for_radius": 33.0,
      "radius_km": 0.6068
    },
    "node/9267193443": {
      "name": "Dergez trgovina",
      "brand": "",
      "rating": 4.5,
      "user_ratings_total": 92,
      "formatted_address": "Trg bana Josipa Jelačića 11, 48363, Podravske Sesvete, Croatia",
      "coordinates": [
        17.2105091,
        46.00195
      ],
      "value_for_radius": 92.0,
      "radius_km": 1.014
    },
    "node/9392589356": {
      "name": "Studenac Market",
      "brand": "",
      "rating": 4.7,
      "user_ratings_total": 3,
      "formatted_address": "Ul. Novi Brežanec 6, 48000, Koprivnica, Croatia",
      "coordinates": [
        16.8328133,
        46.1536374
      ],
      "value_for_radius": 3.0,
      "radius_km": 0.5
    },
    "node/9804228487": {
      "name": "INTERSPAR",
      "brand": "Interspar",
      "rating": 4.4,
      "user_ratings_total": 2232,
      "formatted_address": "Radnička cesta 8, 48000, Koprivnica, Croatia",
      "coordinates": [
        16.8342652,
        46.1464284
      ],
      "value_for_radius": 2232.0,
      "radius_km": 4.7534
    },
    "node/9837851184": {
      "name": "Robin market 53",
      "brand": "",
      "rating": 4.8,
      "user_ratings_total": 11,
      "formatted_address": "Ul. Mojsija Baltića 1, 48260, Križevci, Croatia",
      "coordinates": [
        16.5460015,
        46.0260065
      ],
      "value_for_radius": 11.0,
      "radius_km": 0.5
    },
    "node/10779670469": {
      "name": "Super Konzum",
      "brand": "Konzum",
      "rating": 4.2,
      "user_ratings_total": 9,
      "formatted_address": "Ul. kralja Tomislava 56a, 48260, Križevci, Croatia",
      "coordinates": [
        16.5441173,
        46.0169365
      ],
      "value_for_radius": 9.0,
      "radius_km": 0.5
    },
    "node/11775261106": {
      "name": "Sloga",
      "brand": "",
      "rating": 4.2,
      "user_ratings_total": 28,
      "formatted_address": "Kolodvorska ul. 76, 48361, Kalinovac, Croatia",
      "coordinates": [
        17.1106521,
        46.0178299
      ],
      "value_for_radius": 28.0,
      "radius_km": 0.5557
    },
    "node/11775268935": {
      "name": "Dergez trgovina",
      "brand": "",
      "rating": 4.6,
      "user_ratings_total": 19,
      "formatted_address": "Dravska ul. 3, 48361, Kalinovac, Croatia",
      "coordinates": [
        17.1134263,
        46.0256128
      ],
      "value_for_radius": 19.0,
      "radius_km": 0.5
    },
    "node/11775286978": {
      "name": "Dergez trgovina",
      "brand": "",
      "rating": 4.6,
      "user_ratings_total": 19,
      "formatted_address": "Dravska ul. 3, 48361, Kalinovac, Croatia",
      "coordinates": [
        17.1138616,
        46.0255702
      ],
      "value_for_radius": 19.0,
      "radius_km": 0.5
    },
    "node/11775288369": {
      "name": "Studenac Market",
      "brand": "",
      "rating": 3.5,
      "user_ratings_total": 1,
      "formatted_address": "Dravska ul. 4, 48350, Kalinovac, Croatia",
      "coordinates": [
        17.1181761,
        46.0270891
      ],
      "value_for_radius": 1.0,
      "radius_km": 0.5
    },
    "node/11779004820": {
      "name": "Stara Drava d.o.o.",
      "brand": "",
      "rating": 4.5,
      "user_ratings_total": 104,
      "formatted_address": "Ul. Drenovica 32, 48355, Novo Virje, Croatia",
      "coordinates": [
        17.1390643,
        46.1001477
      ],
      "value_for_radius": 104.0,
      "radius_km": 0.9613
    },
    "node/11779489591": {
      "name": "Dergez trgovina",
      "brand": "",
      "rating": 4.5,
      "user_ratings_total": 51,
      "formatted_address": "Dravska Ul. 65, 48356, Ferdinandovac, Croatia",
      "coordinates": [
        17.1895646,
        46.0606086
      ],
      "value_for_radius": 51.0,
      "radius_km": 0.7455
    },
    "node/11779490406": {
      "name": "Studenac Market",
      "brand": "",
      "rating": 4,
      "user_ratings_total": 2,
      "formatted_address": "Trg Slobode 27, 48350, Ferdinandovac, Croatia",
      "coordinates": [
        17.1905405,
        46.0607476
      ],
      "value_for_radius": 2.0,
      "radius_km": 0.5
    },
    "node/11779512696": {
      "name": "Stara Drava d.o.o.",
      "brand": "Studenac",
      "rating": 4.5,
      "user_ratings_total": 104,
      "formatted_address": "Ul. Drenovica 32, 48355, Novo Virje, Croatia",
      "coordinates": [
        17.1368251,
        46.09986
      ],
      "value_for_radius": 104.0,
      "radius_km": 0.9613
    },
    "node/12085232210": {
      "name": "Robin Market 44",
      "brand": "",
      "rating": 4.4,
      "user_ratings_total": 21,
      "formatted_address": "Trg Sidonije Rubido Erdody 3, 48268, Gornja Rijeka, Croatia",
      "coordinates": [
        16.3919249,
        46.1098445
      ],
      "value_for_radius": 21.0,
      "radius_km": 0.5
    },
    "node/12147658121": {
      "name": "Robin Market 35",
      "brand": "",
      "rating": 4.5,
      "user_ratings_total": 6,
      "formatted_address": "Lepavina 99, 48306, Lepavina, Croatia",
      "coordinates": [
        16.6845119,
        46.0986089
      ],
      "value_for_radius": 6.0,
      "radius_km": 0.5
    },
    "node/12316085415": {
      "name": "Studenac Market",
      "brand": "",
      "rating": 3.8,
      "user_ratings_total": 9,
      "formatted_address": "Ul. Stjepana Radića 7, 48000, Gola, Croatia",
      "coordinates": [
        17.0598599,
        46.1980949
      ],
      "value_for_radius": 9.0,
      "radius_km": 0.5
    },
    "node/12372532427": {
      "name": "Studenac Market",
      "brand": "Studenac",
      "rating": 4.3,
      "user_ratings_total": 3,
      "formatted_address": "Duga Rijeka 3, 48000, Duga Rijeka, Croatia",
      "coordinates": [
        16.5937071,
        46.1806831
      ],
      "value_for_radius": 3.0,
      "radius_km": 0.5
    },
    "node/12372535038": {
      "name": "Studenac Market",
      "brand": "Studenac",
      "rating": 3,
      "user_ratings_total": 1,
      "formatted_address": "Andrije Palmovića 17, 48000, Rasinja, Croatia",
      "coordinates": [
        16.7082358,
        46.1873862
      ],
      "value_for_radius": 1.0,
      "radius_km": 0.5
    },
    "node/12410057078": {
      "name": "Robin Market 48",
      "brand": "",
      "rating": 4.3,
      "user_ratings_total": 73,
      "formatted_address": "Trg Slobode 2, 48213, Cirkvena, Croatia",
      "coordinates": [
        16.6584448,
        45.9352015
      ],
      "value_for_radius": 73.0,
      "radius_km": 0.9029
    },
    "node/12412755421": {
      "name": "Studenac Market",
      "brand": "",
      "rating": 5,
      "user_ratings_total": 3,
      "formatted_address": "Ul. Stjepana Radića 110, 48350, Đurđevac, Croatia",
      "coordinates": [
        17.0649393,
        46.0333068
      ],
      "value_for_radius": 3.0,
      "radius_km": 0.5
    },
    "node/12453191584": {
      "name": "Robin Market 61",
      "brand": "",
      "rating": 4.9,
      "user_ratings_total": 21,
      "formatted_address": "Čarda ul. 2, 48000, Koprivnica, Croatia",
      "coordinates": [
        16.8413222,
        46.1760384
      ],
      "value_for_radius": 21.0,
      "radius_km": 0.5
    },
    "node/12495479022": {
      "name": "Robin market 53",
      "brand": "",
      "rating": 4.8,
      "user_ratings_total": 11,
      "formatted_address": "Ul. Mojsija Baltića 1, 48260, Križevci, Croatia",
      "coordinates": [
        16.5484206,
        46.0246381
      ],
      "value_for_radius": 11.0,
      "radius_km": 0.5
    },
    "node/12538802906": {
      "name": "Dergez trgovina",
      "brand": "",
      "rating": 4.5,
      "user_ratings_total": 100,
      "formatted_address": "Ljudevita Gaja 10, 48326, Virje, Croatia",
      "coordinates": [
        16.9896312,
        46.0672245
      ],
      "value_for_radius": 100.0,
      "radius_km": 0.8364
    },
    "node/12538825424": {
      "name": "Studenac Market",
      "brand": "",
      "rating": 4.5,
      "user_ratings_total": 4,
      "formatted_address": "Ključeci 1, 48350, Molve, Croatia",
      "coordinates": [
        17.0310447,
        46.1065445
      ],
      "value_for_radius": 4.0,
      "radius_km": 0.5
    },
    "node/12538931824": {
      "name": "Stridon promet",
      "brand": "",
      "rating": 4.3,
      "user_ratings_total": 12,
      "formatted_address": "Domžalska 3, 48000, Koprivnica, Croatia",
      "coordinates": [
        16.8170158,
        46.1679468
      ],
      "value_for_radius": 12.0,
      "radius_km": 0.5
    },
    "node/12657258756": {
      "name": "\"PPK\" trgovina",
      "brand": "",
      "rating": 4.4,
      "user_ratings_total": 41,
      "formatted_address": "48326, Virje, Croatia",
      "coordinates": [
        16.9890772,
        46.0657208
      ],
      "value_for_radius": 41.0,
      "radius_km": 0.5
    },
    "node/12657258808": {
      "name": "Dergez trgovina",
      "brand": "",
      "rating": 4.5,
      "user_ratings_total": 100,
      "formatted_address": "Ljudevita Gaja 10, 48326, Virje, Croatia",
      "coordinates": [
        16.9879115,
        46.0663183
      ],
      "value_for_radius": 100.0,
      "radius_km": 0.8231
    },
    "node/12657258819": {
      "name": "Dergez trgovina",
      "brand": "",
      "rating": 4.5,
      "user_ratings_total": 100,
      "formatted_address": "Ljudevita Gaja 10, 48326, Virje, Croatia",
      "coordinates": [
        16.9891758,
        46.069187
      ],
      "value_for_radius": 100.0,
      "radius_km": 0.7871
    }
  },
  "description": "Generated HPO instance for stores whose formatted_address matches '48***'.",
  "id": "ae82c9fc-cd81-4680-bc84-af424a989218",
  "run_info": {
    "status": "Not started",
    "updated_at": "2026-06-17T14:11:11.046975+00:00"
  },
  "settings": {
    "ga": {
      "crossover": {
        "params": {
          "children": [],
          "p": 1,
          "weights": [
            0.4,
            0.4,
            0.2
          ]
        },
        "type": "CompositeCrossover"
      },
      "deterministic": true,
      "eliminator": {
        "params": {
          "elitism": 5
        },
        "type": "EliteEliminator"
      },
      "fitness": {
        "params": {},
        "type": "FastIntersectUnionFitness"
      },
      "generations": 5000,
      "generator": {
        "params": {},
        "type": "AllSundaysHaveWorkGenerator"
      },
      "logger": {
        "params": {},
        "type": "SoutLogger"
      },
      "mutator": {
        "params": {
          "children": [],
          "p": 1,
          "weights": [
            1
          ]
        },
        "type": "CompositeMutator"
      },
      "newChromosomes": 2,
      "numThreads": 4,
      "populationSize": 100,
      "selection": {
        "params": {
          "tournamentSize": 3
        },
        "type": "TournamentSelection"
      },
      "stagnationFraction": 0.2,
      "timelimit": 300
    },
    "general": {
      "MAX_CLUSTER_DISTANCE": 3,
      "MAX_CLUSTER_JOIN_DISTANCE": 10
    }
  },
  "status": "initialized",
  "username": "jetpans",
  "value_calculator": null,
  "value_for_radius_calculator": "return store.get('user_ratings_total', 5) * 1"
}
