{
  "constraints": {
    "MAX_DOESNT_WORK": 36,
    "MAX_WORKS": 16,
    "SUNDAYS": 52,
    "YEAR": 2026,
    "way/48422194": {
      "doesnt_work": [
        2,
        3,
        6,
        7,
        9,
        14,
        15,
        29,
        34,
        36,
        39,
        41,
        45,
        48,
        51
      ],
      "works": [
        1,
        17,
        47
      ]
    },
    "way/48422205": {
      "doesnt_work": [
        0,
        1,
        2,
        3,
        5,
        6,
        8,
        9,
        10,
        11,
        12,
        13,
        15,
        18,
        20,
        22,
        23,
        24,
        25,
        27,
        29,
        33,
        38,
        40,
        43,
        46,
        47,
        50
      ],
      "works": [
        14,
        26,
        34,
        41,
        44,
        45
      ]
    },
    "way/48452158": {
      "doesnt_work": [
        7,
        8,
        10,
        13,
        16,
        17,
        20,
        21,
        25,
        26,
        27,
        28,
        33,
        43
      ],
      "works": [
        2,
        4,
        12,
        23,
        36,
        39,
        40,
        42,
        45
      ]
    },
    "way/113968555": {
      "doesnt_work": [
        10,
        14,
        15,
        17,
        24,
        29,
        34,
        35,
        42,
        48
      ],
      "works": [
        38,
        40
      ]
    },
    "way/152801727": {
      "doesnt_work": [
        0,
        1,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        16,
        18,
        19,
        22,
        23,
        26,
        27,
        28,
        29,
        30,
        33,
        34,
        35,
        36,
        37,
        38,
        39,
        40,
        41,
        42,
        43,
        44,
        45,
        46,
        47,
        48
      ],
      "works": [
        2,
        3,
        4,
        13,
        14,
        17,
        20,
        25,
        49,
        51
      ]
    },
    "way/261730760": {
      "doesnt_work": [],
      "works": [
        7,
        10,
        18,
        21,
        27,
        29,
        41,
        49
      ]
    },
    "way/262570650": {
      "doesnt_work": [
        0,
        1,
        2,
        4,
        8,
        9,
        10,
        12,
        14,
        17,
        18,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        28,
        29,
        31,
        33,
        35,
        36,
        37,
        38,
        39,
        42,
        43,
        45,
        47,
        50
      ],
      "works": [
        6,
        11,
        19,
        32,
        40,
        46,
        48,
        51
      ]
    },
    "way/280994237": {
      "doesnt_work": [
        0,
        1,
        2,
        4,
        8,
        17,
        22,
        26,
        29,
        30,
        32,
        37,
        43,
        48,
        51
      ],
      "works": [
        7,
        12,
        13,
        19,
        23,
        25,
        27,
        28,
        33,
        34,
        38,
        39,
        41,
        42,
        44,
        46
      ]
    },
    "way/351897311": {
      "doesnt_work": [
        1,
        2,
        3,
        5,
        7,
        9,
        12,
        16,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
        33,
        35,
        37,
        38,
        39,
        41,
        43,
        44,
        45,
        46,
        47,
        48,
        49,
        50,
        51
      ],
      "works": [
        4,
        8,
        13,
        15,
        17,
        31,
        32,
        34,
        36,
        42
      ]
    },
    "way/421547606": {
      "doesnt_work": [],
      "works": [
        3,
        34,
        41
      ]
    },
    "way/421594574": {
      "doesnt_work": [
        0,
        3,
        10,
        13,
        25,
        26,
        27,
        31,
        32,
        43
      ],
      "works": [
        15,
        48
      ]
    },
    "way/534211945": {
      "doesnt_work": [
        1,
        2,
        3,
        5,
        6,
        7,
        9,
        10,
        12,
        13,
        16,
        19,
        20,
        21,
        22,
        23,
        24,
        26,
        30,
        31,
        33,
        34,
        36,
        37,
        38,
        40,
        41,
        43,
        45,
        47,
        48
      ],
      "works": [
        18,
        27,
        29,
        35,
        42,
        44,
        50,
        51
      ]
    },
    "way/569687122": {
      "doesnt_work": [
        1,
        2,
        3,
        5,
        6,
        7,
        9,
        10,
        11,
        12,
        17,
        18,
        21,
        22,
        24,
        26,
        28,
        30,
        32,
        34,
        35,
        37,
        38,
        39,
        40,
        43,
        44,
        47,
        48
      ],
      "works": [
        0,
        4,
        8,
        13,
        15,
        16,
        19,
        20,
        25,
        29,
        41,
        42,
        45,
        46,
        50,
        51
      ]
    },
    "way/717264992": {
      "doesnt_work": [
        0,
        1,
        2,
        3,
        4,
        5,
        8,
        10,
        11,
        14,
        18,
        19,
        20,
        24,
        25,
        26,
        27,
        29,
        30,
        31,
        33,
        34,
        35,
        37,
        41,
        42,
        44,
        46,
        47,
        49,
        51
      ],
      "works": [
        13,
        16,
        21,
        32,
        38,
        40,
        43,
        45,
        50
      ]
    },
    "way/733807132": {
      "doesnt_work": [
        1,
        12,
        14,
        19,
        27,
        32,
        46,
        47,
        51
      ],
      "works": [
        2,
        6,
        13,
        15,
        22,
        26,
        35,
        42,
        43,
        49,
        50
      ]
    },
    "way/1119626342": {
      "doesnt_work": [
        1,
        5,
        16,
        18,
        21,
        23,
        26,
        27,
        31,
        35,
        40,
        47
      ],
      "works": [
        2,
        6,
        10,
        14,
        24,
        30,
        44,
        50
      ]
    },
    "way/1259174963": {
      "doesnt_work": [
        2,
        3,
        8,
        9,
        10,
        23,
        26,
        28,
        30,
        35,
        36,
        42,
        47,
        48,
        49,
        50
      ],
      "works": [
        1,
        7,
        11,
        16,
        21,
        25,
        32,
        34,
        37,
        41,
        43
      ]
    },
    "node/2682122123": {
      "doesnt_work": [
        24,
        25,
        26,
        32,
        35,
        44,
        51
      ],
      "works": [
        0,
        4,
        12,
        20,
        21,
        23,
        27,
        33,
        34,
        39,
        42,
        43,
        46
      ]
    },
    "node/2683774161": {
      "doesnt_work": [
        0,
        14,
        19,
        20,
        28,
        30,
        38,
        39,
        40,
        43,
        49
      ],
      "works": [
        12,
        24,
        26,
        42
      ]
    },
    "node/2700234204": {
      "doesnt_work": [
        1,
        2,
        6,
        8,
        11,
        15,
        17,
        18,
        22,
        24,
        27,
        38,
        39,
        41,
        44,
        45,
        48,
        49
      ],
      "works": [
        5,
        10,
        13,
        28,
        29,
        30,
        32,
        42,
        43,
        50
      ]
    },
    "node/2702842700": {
      "doesnt_work": [
        4,
        5,
        7,
        10,
        14,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        26,
        28,
        29,
        32,
        33,
        34,
        37,
        38,
        39,
        42,
        43,
        46,
        48,
        49,
        51
      ],
      "works": [
        0,
        6,
        9,
        12,
        15,
        24,
        25,
        31,
        36,
        40,
        41,
        44,
        45
      ]
    },
    "node/2702842702": {
      "doesnt_work": [
        2,
        4,
        5,
        6,
        8,
        9,
        14,
        16,
        19,
        20,
        22,
        23,
        24,
        26,
        30,
        38,
        42
      ],
      "works": [
        15,
        17,
        31,
        33,
        40,
        49,
        51
      ]
    },
    "node/2704154696": {
      "doesnt_work": [
        0,
        2,
        4,
        6,
        7,
        8,
        9,
        10,
        12,
        14,
        15,
        16,
        17,
        18,
        20,
        22,
        23,
        27,
        28,
        31,
        32,
        33,
        35,
        41,
        42,
        44,
        45,
        46,
        49,
        50
      ],
      "works": [
        1,
        3,
        13,
        21,
        24,
        26,
        29,
        34,
        36,
        37,
        43,
        47,
        51
      ]
    },
    "node/2725536059": {
      "doesnt_work": [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        13,
        14,
        15,
        17,
        18,
        20,
        21,
        22,
        23,
        25,
        27,
        30,
        31,
        35,
        40,
        44,
        51
      ],
      "works": [
        16
      ]
    },
    "node/2761542679": {
      "doesnt_work": [
        11,
        14,
        18,
        25,
        32,
        39,
        48
      ],
      "works": [
        8,
        15,
        30,
        42
      ]
    },
    "node/2764497322": {
      "doesnt_work": [
        1,
        21,
        26,
        38,
        39,
        45
      ],
      "works": [
        10,
        19,
        49
      ]
    },
    "node/3419315401": {
      "doesnt_work": [
        28,
        46
      ],
      "works": [
        4,
        6,
        7,
        12,
        15,
        19,
        36,
        37,
        38,
        40,
        44,
        45
      ]
    },
    "node/4345053366": {
      "doesnt_work": [
        14,
        20,
        36,
        37,
        39,
        40,
        45,
        46,
        51
      ],
      "works": [
        0,
        4,
        6,
        21,
        23,
        26,
        27,
        29,
        31,
        32,
        41,
        42,
        50
      ]
    },
    "node/4375893598": {
      "doesnt_work": [
        0,
        1,
        2,
        7,
        8,
        12,
        14,
        18,
        19,
        21,
        24,
        25,
        26,
        27,
        30,
        33,
        38,
        39,
        40,
        42,
        44,
        47,
        48,
        51
      ],
      "works": [
        5,
        15,
        17,
        20,
        28,
        29,
        36,
        50
      ]
    },
    "node/4496910688": {
      "doesnt_work": [
        4,
        7,
        8,
        9,
        10,
        11,
        12,
        21,
        22,
        24,
        29,
        31,
        32,
        34,
        38,
        40,
        42,
        43,
        45,
        46,
        49,
        51
      ],
      "works": [
        1,
        5,
        14,
        15,
        18,
        19,
        23,
        25,
        28,
        30,
        33,
        35,
        37,
        44,
        50
      ]
    },
    "node/5289724107": {
      "doesnt_work": [
        0,
        1,
        2,
        3,
        5,
        6,
        8,
        10,
        11,
        16,
        20,
        21,
        22,
        33,
        34,
        35,
        37,
        38,
        40,
        41,
        46,
        48,
        49
      ],
      "works": [
        12,
        14,
        18
      ]
    },
    "node/6282640507": {
      "doesnt_work": [
        21,
        33,
        35,
        38,
        39,
        47,
        49
      ],
      "works": [
        3,
        4,
        5,
        7,
        9,
        15,
        19,
        25,
        31,
        36,
        40,
        42,
        43,
        46,
        50
      ]
    },
    "node/6343936599": {
      "doesnt_work": [
        0,
        7,
        14,
        15,
        20,
        21,
        25,
        29,
        33,
        48
      ],
      "works": [
        3,
        5,
        6,
        13,
        16,
        19,
        27,
        36,
        37,
        39,
        40,
        42,
        46,
        51
      ]
    },
    "node/6736193892": {
      "doesnt_work": [
        1,
        6,
        11,
        20,
        23,
        46,
        50
      ],
      "works": [
        2,
        4,
        12,
        14,
        16,
        18,
        27,
        29,
        37,
        40,
        44,
        45,
        48,
        49,
        51
      ]
    },
    "node/6736193895": {
      "doesnt_work": [
        1,
        2,
        5,
        7,
        16,
        17,
        20,
        21,
        26,
        28,
        29,
        30,
        32,
        33,
        35,
        37,
        49,
        51
      ],
      "works": [
        19,
        36,
        38,
        47,
        50
      ]
    },
    "node/6855168729": {
      "doesnt_work": [
        2,
        5,
        11,
        17,
        22,
        27,
        28,
        30,
        31,
        33,
        36,
        37,
        41,
        46,
        47,
        48,
        49
      ],
      "works": []
    },
    "node/7900274665": {
      "doesnt_work": [
        0,
        1,
        5,
        7,
        8,
        9,
        11,
        14,
        15,
        16,
        17,
        19,
        22,
        23,
        27,
        28,
        29,
        30,
        33,
        34,
        37,
        39,
        40,
        43,
        45,
        46,
        47,
        48,
        49
      ],
      "works": [
        2,
        6,
        10,
        18,
        20,
        21,
        25,
        26,
        31,
        35,
        42,
        44,
        51
      ]
    },
    "node/8232192130": {
      "doesnt_work": [
        0,
        6,
        8,
        10,
        11,
        15,
        19,
        20,
        27,
        30,
        32,
        36,
        42,
        48,
        51
      ],
      "works": [
        1,
        38,
        40
      ]
    },
    "node/9606423863": {
      "doesnt_work": [
        0,
        3,
        5,
        6,
        13,
        14,
        16,
        18,
        20,
        21,
        22,
        23,
        25,
        27,
        28,
        31,
        33,
        34,
        36,
        37,
        39,
        40,
        44,
        46,
        47,
        51
      ],
      "works": [
        4,
        8,
        9,
        12,
        15,
        17,
        24,
        26,
        29,
        30,
        32,
        35,
        38,
        45,
        48,
        50
      ]
    },
    "node/9847850917": {
      "doesnt_work": [
        0,
        3,
        5,
        7,
        8,
        10,
        12,
        13,
        15,
        16,
        18,
        19,
        21,
        23,
        25,
        27,
        28,
        29,
        31,
        33,
        34,
        35,
        36,
        37,
        38,
        39,
        46,
        47,
        48,
        50,
        51
      ],
      "works": [
        2,
        9,
        14,
        20,
        24,
        26,
        30,
        41,
        42,
        44,
        45,
        49
      ]
    },
    "node/9885671669": {
      "doesnt_work": [
        1,
        2,
        3,
        5,
        6,
        10,
        14,
        19,
        20,
        21,
        23,
        24,
        28,
        29,
        42,
        47,
        48,
        49
      ],
      "works": [
        15,
        40
      ]
    },
    "node/10053710312": {
      "doesnt_work": [
        5,
        9,
        10,
        11,
        14,
        16,
        25,
        34,
        41,
        43,
        48
      ],
      "works": [
        15,
        26,
        33,
        36
      ]
    },
    "node/10053734529": {
      "doesnt_work": [
        1,
        5,
        9,
        11,
        12,
        14,
        15,
        21,
        24,
        25,
        30,
        32,
        36,
        37,
        38,
        39,
        44,
        45,
        51
      ],
      "works": [
        0,
        4,
        10,
        16,
        18,
        22,
        28,
        29,
        34,
        40,
        42,
        43,
        49,
        50
      ]
    },
    "node/10053734581": {
      "doesnt_work": [
        2,
        3,
        4,
        5,
        6,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        16,
        17,
        18,
        19,
        22,
        23,
        28,
        29,
        30,
        31,
        32,
        35,
        36,
        37,
        38,
        40,
        43,
        44,
        45,
        46,
        47,
        49,
        50,
        51
      ],
      "works": []
    },
    "node/10728443694": {
      "doesnt_work": [
        0,
        4,
        5,
        7,
        8,
        9,
        14,
        17,
        20,
        23,
        25,
        27,
        32,
        33,
        34,
        37,
        38,
        42,
        44,
        49,
        50
      ],
      "works": [
        16,
        18,
        30,
        47,
        51
      ]
    },
    "node/10767143515": {
      "doesnt_work": [
        9,
        24,
        32,
        36
      ],
      "works": [
        1,
        6,
        14,
        20,
        23,
        30,
        35,
        39,
        40,
        43,
        44,
        47
      ]
    },
    "node/10767143516": {
      "doesnt_work": [
        10,
        17,
        26,
        27,
        33,
        38
      ],
      "works": [
        2,
        7,
        19,
        31
      ]
    },
    "node/10767143521": {
      "doesnt_work": [
        4,
        8,
        11,
        15,
        19,
        28,
        29,
        33,
        35,
        40,
        44,
        45,
        51
      ],
      "works": [
        2,
        6,
        9,
        17,
        23,
        26,
        31,
        37,
        39,
        41,
        46,
        47,
        50
      ]
    },
    "node/10767143522": {
      "doesnt_work": [
        0,
        2,
        6,
        7,
        9,
        10,
        11,
        12,
        14,
        16,
        17,
        18,
        19,
        20,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
        31,
        33,
        34,
        35,
        37,
        39,
        44,
        45,
        46,
        47,
        48,
        51
      ],
      "works": [
        1,
        3,
        4,
        5,
        8,
        13,
        15,
        21,
        36,
        38,
        40,
        41,
        42,
        49
      ]
    },
    "node/10767143523": {
      "doesnt_work": [
        4,
        5,
        7,
        8,
        9,
        11,
        12,
        13,
        15,
        16,
        17,
        18,
        21,
        22,
        23,
        24,
        26,
        27,
        28,
        34,
        36,
        37,
        38,
        44,
        45,
        48,
        50
      ],
      "works": [
        1,
        2,
        3,
        14,
        19,
        25,
        29,
        30,
        32,
        33,
        39,
        41,
        42,
        46
      ]
    },
    "node/10767143524": {
      "doesnt_work": [
        1,
        4,
        5,
        6,
        9,
        11,
        17,
        18,
        19,
        22,
        24,
        25,
        31,
        32,
        33,
        36,
        38,
        40,
        41,
        42,
        43,
        45,
        48,
        49,
        50
      ],
      "works": [
        14,
        21,
        26,
        27,
        28,
        29
      ]
    },
    "node/10767143527": {
      "doesnt_work": [
        8,
        9,
        10,
        11,
        15,
        16,
        21,
        23,
        24,
        25,
        28,
        29,
        30,
        31,
        32,
        37,
        39,
        40,
        45,
        47,
        48,
        50
      ],
      "works": [
        3,
        7,
        18,
        19,
        22,
        26,
        27,
        38,
        42,
        51
      ]
    },
    "node/10793625756": {
      "doesnt_work": [
        0,
        1,
        4,
        5,
        9,
        11,
        17,
        19,
        21,
        22,
        25,
        33,
        36,
        42,
        44,
        50,
        51
      ],
      "works": []
    },
    "node/11145771905": {
      "doesnt_work": [
        3,
        5,
        6,
        8,
        9,
        11,
        17,
        18,
        22,
        30,
        32,
        33,
        34,
        37,
        41,
        42,
        44,
        47,
        48
      ],
      "works": [
        10,
        21,
        23,
        24,
        26,
        29
      ]
    },
    "node/11309376324": {
      "doesnt_work": [
        0,
        2,
        3,
        9,
        14,
        15,
        17,
        20,
        28,
        34,
        36,
        38,
        40,
        41,
        45,
        46,
        50,
        51
      ],
      "works": [
        7,
        22,
        27
      ]
    },
    "node/11338772769": {
      "doesnt_work": [
        1,
        2,
        3,
        4,
        5,
        6,
        9,
        13,
        14,
        15,
        16,
        17,
        18,
        22,
        23,
        26,
        29,
        30,
        32,
        33,
        34,
        35,
        37,
        38,
        39,
        40,
        41,
        42,
        43,
        44,
        46,
        48,
        49,
        51
      ],
      "works": [
        0,
        7,
        8,
        11,
        20,
        24,
        27,
        31,
        47
      ]
    },
    "node/11434741150": {
      "doesnt_work": [
        12,
        16,
        20,
        29,
        42,
        43,
        48
      ],
      "works": [
        4,
        5,
        10,
        14,
        19,
        21,
        25,
        32,
        33,
        40,
        46,
        47
      ]
    },
    "node/11829811618": {
      "doesnt_work": [
        4,
        10,
        13,
        31,
        32,
        34,
        39,
        40,
        41,
        43,
        44
      ],
      "works": [
        9,
        12,
        16
      ]
    },
    "node/11829955008": {
      "doesnt_work": [
        5,
        27,
        39
      ],
      "works": [
        4,
        9,
        17,
        19,
        20,
        28,
        30,
        40,
        48,
        51
      ]
    },
    "node/11985614785": {
      "doesnt_work": [
        1,
        6,
        7,
        8,
        9,
        10,
        11,
        13,
        14,
        16,
        19,
        20,
        21,
        22,
        26,
        27,
        30,
        32,
        33,
        36,
        37,
        38,
        40,
        42,
        43,
        44,
        45,
        46,
        47,
        49,
        50,
        51
      ],
      "works": [
        2,
        3,
        4,
        5,
        18,
        23,
        28,
        29,
        41
      ]
    },
    "node/11985614792": {
      "doesnt_work": [
        2,
        7,
        8,
        12,
        13,
        15,
        19,
        20,
        23,
        25,
        26,
        27,
        30,
        36,
        39,
        42,
        45,
        48
      ],
      "works": [
        3,
        4,
        6,
        21,
        24,
        35,
        38,
        40,
        41,
        43,
        44,
        49,
        50
      ]
    },
    "node/12073597246": {
      "doesnt_work": [
        3,
        6,
        9,
        17,
        29,
        34,
        37,
        43,
        48
      ],
      "works": [
        1,
        5,
        8,
        11,
        12,
        13,
        14,
        19,
        21,
        23,
        27,
        31,
        32,
        41,
        42,
        46
      ]
    },
    "node/12073605189": {
      "doesnt_work": [
        2,
        12,
        17,
        20,
        26,
        29,
        31,
        43,
        48,
        50,
        51
      ],
      "works": [
        9,
        10,
        24,
        38
      ]
    },
    "node/12085991804": {
      "doesnt_work": [
        0,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        13,
        14,
        16,
        17,
        18,
        20,
        21,
        26,
        27,
        28,
        31,
        32,
        33,
        35,
        36,
        37,
        38,
        39,
        40,
        41,
        45,
        46,
        47,
        50,
        51
      ],
      "works": [
        12,
        15,
        19,
        23,
        30,
        34,
        43
      ]
    },
    "node/12233204077": {
      "doesnt_work": [
        0,
        3,
        8,
        11,
        27,
        38,
        40,
        47,
        51
      ],
      "works": [
        1,
        5,
        6,
        14,
        15,
        20,
        21,
        23,
        24,
        32,
        41,
        50
      ]
    },
    "node/12328882581": {
      "doesnt_work": [
        3,
        7,
        9,
        13,
        15,
        18,
        19,
        26,
        27,
        29,
        33,
        35,
        38,
        42,
        44,
        46
      ],
      "works": []
    }
  },
  "created_at": "2026-06-17T14:08:28.431862+00:00",
  "data": {
    "way/48422194": {
      "name": "SPAR supermarket Rijeka Osječka",
      "brand": "Spar",
      "rating": 4,
      "user_ratings_total": 1279,
      "formatted_address": "Osječka ul. 29, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4278921,
        45.3392484
      ],
      "value_for_radius": 1279.0,
      "radius_km": 1.0127
    },
    "way/48422205": {
      "name": "Plodine",
      "brand": "Plodine",
      "rating": 3.8,
      "user_ratings_total": 975,
      "formatted_address": "Osječka ul. 50, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4277848,
        45.3406404
      ],
      "value_for_radius": 975.0,
      "radius_km": 0.9051
    },
    "way/48452158": {
      "name": "Lidl",
      "brand": "Lidl",
      "rating": 4.4,
      "user_ratings_total": 2465,
      "formatted_address": "Osječka ul. 67/A, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4183335,
        45.348922
      ],
      "value_for_radius": 2465.0,
      "radius_km": 2.2382
    },
    "way/113968555": {
      "name": "Plodine",
      "brand": "Plodine",
      "rating": 3.9,
      "user_ratings_total": 1862,
      "formatted_address": "Vukovarska ul. 87, 51000, Rijeka, Croatia",
      "coordinates": [
        14.413157,
        45.3428816
      ],
      "value_for_radius": 1862.0,
      "radius_km": 1.4846
    },
    "way/152801727": {
      "name": "Kaufland Rijeka",
      "brand": "Kaufland",
      "rating": 4.2,
      "user_ratings_total": 4101,
      "formatted_address": "Zametska ul. 44, 51000, Rijeka, Croatia",
      "coordinates": [
        14.3986357,
        45.3407383
      ],
      "value_for_radius": 4101.0,
      "radius_km": 3.1552
    },
    "way/261730760": {
      "name": "Birota",
      "brand": "",
      "rating": 4.2,
      "user_ratings_total": 20,
      "formatted_address": "Primorska ul. 20, 51000, Rijeka, Croatia",
      "coordinates": [
        14.3816863,
        45.3512611
      ],
      "value_for_radius": 20.0,
      "radius_km": 0.5
    },
    "way/262570650": {
      "name": "Plodine",
      "brand": "Plodine",
      "rating": 3.7,
      "user_ratings_total": 1331,
      "formatted_address": "Ul. Bartola Kašića 7, 51000, Rijeka, Croatia",
      "coordinates": [
        14.3658183,
        45.3554437
      ],
      "value_for_radius": 1331.0,
      "radius_km": 2.3019
    },
    "way/280994237": {
      "name": "Trgovina Krk d.d.",
      "brand": "",
      "rating": 4.2,
      "user_ratings_total": 36,
      "formatted_address": "Ul. Ratka Petrovića 27, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4830904,
        45.3235857
      ],
      "value_for_radius": 36.0,
      "radius_km": 0.5
    },
    "way/351897311": {
      "name": "Brodokomerc Nova",
      "brand": "",
      "rating": 3.2,
      "user_ratings_total": 15,
      "formatted_address": "Baštijanova ul. 26, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4419193,
        45.3326256
      ],
      "value_for_radius": 15.0,
      "radius_km": 0.5
    },
    "way/421547606": {
      "name": "Lidl",
      "brand": "",
      "rating": 4.2,
      "user_ratings_total": 1872,
      "formatted_address": "Ul. Petra Jurčića 2a, 51000, Rijeka, Croatia",
      "coordinates": [
        14.3929199,
        45.3443021
      ],
      "value_for_radius": 1872.0,
      "radius_km": 1.8368
    },
    "way/421594574": {
      "name": "Plodine",
      "brand": "Plodine",
      "rating": 3.4,
      "user_ratings_total": 29,
      "formatted_address": "Zametska ul. 96A, 51000, Rijeka, Croatia",
      "coordinates": [
        14.3900889,
        45.34339
      ],
      "value_for_radius": 29.0,
      "radius_km": 0.5
    },
    "way/534211945": {
      "name": "Lidl",
      "brand": "Lidl",
      "rating": 4.4,
      "user_ratings_total": 2838,
      "formatted_address": "Radnička ul. 35, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4728738,
        45.3165565
      ],
      "value_for_radius": 2838.0,
      "radius_km": 2.5583
    },
    "way/569687122": {
      "name": "INTERSPAR hipermarket Rijeka",
      "brand": "Spar",
      "rating": 4.3,
      "user_ratings_total": 3254,
      "formatted_address": "Ul. Maria Gennaria 18, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4075498,
        45.3447175
      ],
      "value_for_radius": 3254.0,
      "radius_km": 2.6846
    },
    "way/717264992": {
      "name": "Brodokomerc Nova",
      "brand": "",
      "rating": 3.8,
      "user_ratings_total": 68,
      "formatted_address": "Ul. Silva Milenića Lovre 6, 51000, Rijeka, Croatia",
      "coordinates": [
        14.3733002,
        45.3419504
      ],
      "value_for_radius": 68.0,
      "radius_km": 0.5644
    },
    "way/733807132": {
      "name": "Brodokomerc Nova",
      "brand": "",
      "rating": 4.1,
      "user_ratings_total": 46,
      "formatted_address": "Selinari 228, 51000, Rijeka, Croatia",
      "coordinates": [
        14.3860111,
        45.3534254
      ],
      "value_for_radius": 46.0,
      "radius_km": 0.5
    },
    "way/1119626342": {
      "name": "Kaufland",
      "brand": "Kaufland",
      "rating": 4.4,
      "user_ratings_total": 624,
      "formatted_address": "Osječka ul. 39, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4247825,
        45.3410388
      ],
      "value_for_radius": 624.0,
      "radius_km": 0.9626
    },
    "way/1259174963": {
      "name": "INTERSPAR hipermarket Rijeka Krnjevo",
      "brand": "Interspar",
      "rating": 4.3,
      "user_ratings_total": 727,
      "formatted_address": "Liburnijska ul. 1, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4010288,
        45.3382682
      ],
      "value_for_radius": 727.0,
      "radius_km": 0.959
    },
    "node/2682122123": {
      "name": "Brodokomerc Nova",
      "brand": "",
      "rating": 3.9,
      "user_ratings_total": 19,
      "formatted_address": "Ul. Miroslava Krleže 16, 51000, Rijeka, Croatia",
      "coordinates": [
        14.3694843,
        45.3548368
      ],
      "value_for_radius": 19.0,
      "radius_km": 0.5
    },
    "node/2683774161": {
      "name": "Birota 3 , Josipa Mohorića 1A",
      "brand": "PLUS",
      "rating": 3.5,
      "user_ratings_total": 1,
      "formatted_address": "Ul. Josipa Mohorića 1A, 51000, Rijeka, Croatia",
      "coordinates": [
        14.3908495,
        45.3534811
      ],
      "value_for_radius": 1.0,
      "radius_km": 0.5
    },
    "node/2700234204": {
      "name": "Birota",
      "brand": "",
      "rating": 3.5,
      "user_ratings_total": 1,
      "formatted_address": "Ćićarijska ul. 39, 51000, Rijeka, Croatia",
      "coordinates": [
        14.3984081,
        45.3537981
      ],
      "value_for_radius": 1.0,
      "radius_km": 0.5
    },
    "node/2702842700": {
      "name": "Birota 1",
      "brand": "",
      "rating": 4.6,
      "user_ratings_total": 39,
      "formatted_address": "Ul. Blažićevo C 5, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4085313,
        45.3504552
      ],
      "value_for_radius": 39.0,
      "radius_km": 0.5
    },
    "node/2702842702": {
      "name": "Birota",
      "brand": "",
      "rating": 4.4,
      "user_ratings_total": 35,
      "formatted_address": "Pehlin 35, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4034654,
        45.3544103
      ],
      "value_for_radius": 35.0,
      "radius_km": 0.5
    },
    "node/2704154696": {
      "name": "Studenac Market",
      "brand": "Studenac",
      "rating": 3.6,
      "user_ratings_total": 76,
      "formatted_address": "Trpimirova ul. 6, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4375344,
        45.3281175
      ],
      "value_for_radius": 76.0,
      "radius_km": 0.5
    },
    "node/2725536059": {
      "name": "Plodine",
      "brand": "",
      "rating": 3.9,
      "user_ratings_total": 1862,
      "formatted_address": "Vukovarska ul. 87, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4150289,
        45.3447281
      ],
      "value_for_radius": 1862.0,
      "radius_km": 1.5179
    },
    "node/2761542679": {
      "name": "Studenac Market",
      "brand": "",
      "rating": 3.7,
      "user_ratings_total": 29,
      "formatted_address": "Drenovski put 60, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4297686,
        45.3530969
      ],
      "value_for_radius": 29.0,
      "radius_km": 0.5
    },
    "node/2764497322": {
      "name": "Plodine Rijeka Drenova",
      "brand": "",
      "rating": 3.4,
      "user_ratings_total": 20,
      "formatted_address": "Ul. Ružice Mihić 20, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4263687,
        45.3557675
      ],
      "value_for_radius": 20.0,
      "radius_km": 0.5
    },
    "node/3419315401": {
      "name": "Bookstore Ex libris (Knjiga.hr)",
      "brand": "",
      "rating": 4.7,
      "user_ratings_total": 350,
      "formatted_address": "Ul. Riva Boduli 3b, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4418394,
        45.3249295
      ],
      "value_for_radius": 350.0,
      "radius_km": 0.5
    },
    "node/4345053366": {
      "name": "Brodokomerc Nova",
      "brand": "",
      "rating": 3.3,
      "user_ratings_total": 3,
      "formatted_address": "Korzo 36, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4414638,
        45.3295129
      ],
      "value_for_radius": 3.0,
      "radius_km": 0.5
    },
    "node/4375893598": {
      "name": "Plodine",
      "brand": "Konzum",
      "rating": 3.9,
      "user_ratings_total": 181,
      "formatted_address": "Trninina ul. 3, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4431563,
        45.3251388
      ],
      "value_for_radius": 181.0,
      "radius_km": 0.5
    },
    "node/4496910688": {
      "name": "Tommy Supermarket",
      "brand": "Studenac",
      "rating": 3.9,
      "user_ratings_total": 269,
      "formatted_address": "Ul. Fiorella la Guardije 13, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4333936,
        45.3301462
      ],
      "value_for_radius": 269.0,
      "radius_km": 0.7502
    },
    "node/5289724107": {
      "name": "Plodine",
      "brand": "Plodine",
      "rating": 4,
      "user_ratings_total": 1821,
      "formatted_address": "ZTC, Zvonimirova ul. 3, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4066704,
        45.337813
      ],
      "value_for_radius": 1821.0,
      "radius_km": 2.0921
    },
    "node/6282640507": {
      "name": "SPAR",
      "brand": "Spar",
      "rating": 4,
      "user_ratings_total": 629,
      "formatted_address": "Ul. Riva Boduli 1, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4423341,
        45.3254816
      ],
      "value_for_radius": 629.0,
      "radius_km": 0.5
    },
    "node/6343936599": {
      "name": "SPAR",
      "brand": "",
      "rating": 4,
      "user_ratings_total": 629,
      "formatted_address": "Ul. Riva Boduli 1, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4459633,
        45.3263333
      ],
      "value_for_radius": 629.0,
      "radius_km": 1.0151
    },
    "node/6736193892": {
      "name": "Brodokomerc Nova",
      "brand": "",
      "rating": 4.6,
      "user_ratings_total": 5,
      "formatted_address": "Ul. Braće Bačić 33, 51000, Rijeka, Croatia",
      "coordinates": [
        14.3820597,
        45.3440282
      ],
      "value_for_radius": 5.0,
      "radius_km": 0.5
    },
    "node/6736193895": {
      "name": "Lidl",
      "brand": "Lidl",
      "rating": 4.2,
      "user_ratings_total": 1872,
      "formatted_address": "Ul. Petra Jurčića 2a, 51000, Rijeka, Croatia",
      "coordinates": [
        14.3899249,
        45.342747
      ],
      "value_for_radius": 1872.0,
      "radius_km": 1.8344
    },
    "node/6855168729": {
      "name": "Ultra",
      "brand": "Tommy",
      "rating": 3.9,
      "user_ratings_total": 67,
      "formatted_address": "Tizianova ul. 2, 51000, Rijeka, Croatia",
      "coordinates": [
        14.434548,
        45.330489
      ],
      "value_for_radius": 67.0,
      "radius_km": 0.5
    },
    "node/7900274665": {
      "name": "Plodine",
      "brand": "Plodine",
      "rating": 3.7,
      "user_ratings_total": 1469,
      "formatted_address": "Ul. Martina Kontuša 5, 51000, Rijeka, Croatia",
      "coordinates": [
        14.470478,
        45.3243092
      ],
      "value_for_radius": 1469.0,
      "radius_km": 1.5604
    },
    "node/8232192130": {
      "name": "SPAR",
      "brand": "Konzum",
      "rating": 4,
      "user_ratings_total": 629,
      "formatted_address": "Ul. Riva Boduli 1, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4384756,
        45.3276246
      ],
      "value_for_radius": 629.0,
      "radius_km": 0.8255
    },
    "node/9606423863": {
      "name": "SPAR supermarket Rijeka Martinkovac",
      "brand": "",
      "rating": 4.3,
      "user_ratings_total": 598,
      "formatted_address": "Martinkovac ul. 127, 51000, Rijeka, Croatia",
      "coordinates": [
        14.3626115,
        45.3551059
      ],
      "value_for_radius": 598.0,
      "radius_km": 1.3156
    },
    "node/9847850917": {
      "name": "Birota 1",
      "brand": "",
      "rating": 4.6,
      "user_ratings_total": 39,
      "formatted_address": "Ul. Blažićevo C 5, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4055057,
        45.3506241
      ],
      "value_for_radius": 39.0,
      "radius_km": 0.5
    },
    "node/9885671669": {
      "name": "Brodokomerc Nova",
      "brand": "",
      "rating": 3.3,
      "user_ratings_total": 3,
      "formatted_address": "Korzo 36, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4399786,
        45.327605
      ],
      "value_for_radius": 3.0,
      "radius_km": 0.5
    },
    "node/10053710312": {
      "name": "Smiljana",
      "brand": "",
      "rating": 4.3,
      "user_ratings_total": 114,
      "formatted_address": "Titov trg 12, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4475592,
        45.327252
      ],
      "value_for_radius": 114.0,
      "radius_km": 0.5
    },
    "node/10053734529": {
      "name": "Plodine",
      "brand": "Plodine",
      "rating": 3.9,
      "user_ratings_total": 181,
      "formatted_address": "Trninina ul. 3, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4432881,
        45.3244853
      ],
      "value_for_radius": 181.0,
      "radius_km": 0.5
    },
    "node/10053734581": {
      "name": "Tommy Maximarket",
      "brand": "Tommy",
      "rating": 4.1,
      "user_ratings_total": 281,
      "formatted_address": "Trg Ivana Koblera 1, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4428107,
        45.3268774
      ],
      "value_for_radius": 281.0,
      "radius_km": 0.5
    },
    "node/10728443694": {
      "name": "Plodine",
      "brand": "Plodine",
      "rating": 3.8,
      "user_ratings_total": 241,
      "formatted_address": "Labinska ul. 51A, 51000, Rijeka, Croatia",
      "coordinates": [
        14.3787299,
        45.3426522
      ],
      "value_for_radius": 241.0,
      "radius_km": 1.02
    },
    "node/10767143515": {
      "name": "Plodine",
      "brand": "Studenac",
      "rating": 3.7,
      "user_ratings_total": 1469,
      "formatted_address": "Ul. Martina Kontuša 5, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4680478,
        45.3249218
      ],
      "value_for_radius": 1469.0,
      "radius_km": 1.5737
    },
    "node/10767143516": {
      "name": "Studenac Market",
      "brand": "Studenac",
      "rating": 4.4,
      "user_ratings_total": 37,
      "formatted_address": "Kumičićeva ul. 61-1, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4652784,
        45.322797
      ],
      "value_for_radius": 37.0,
      "radius_km": 0.5
    },
    "node/10767143521": {
      "name": "Tommy Supermarket",
      "brand": "Studenac",
      "rating": 3.9,
      "user_ratings_total": 269,
      "formatted_address": "Ul. Fiorella la Guardije 13, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4306992,
        45.3306832
      ],
      "value_for_radius": 269.0,
      "radius_km": 0.7293
    },
    "node/10767143522": {
      "name": "SPAR",
      "brand": "Studenac",
      "rating": 4,
      "user_ratings_total": 629,
      "formatted_address": "Ul. Riva Boduli 1, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4430627,
        45.3245017
      ],
      "value_for_radius": 629.0,
      "radius_km": 0.5
    },
    "node/10767143523": {
      "name": "SPAR",
      "brand": "Studenac",
      "rating": 4,
      "user_ratings_total": 629,
      "formatted_address": "Ul. Riva Boduli 1, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4417718,
        45.3282568
      ],
      "value_for_radius": 629.0,
      "radius_km": 0.9768
    },
    "node/10767143524": {
      "name": "Tommy Supermarket",
      "brand": "Studenac",
      "rating": 3.9,
      "user_ratings_total": 269,
      "formatted_address": "Ul. Fiorella la Guardije 13, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4387558,
        45.329415
      ],
      "value_for_radius": 269.0,
      "radius_km": 0.6565
    },
    "node/10767143527": {
      "name": "SPAR supermarket Rijeka Osječka",
      "brand": "Studenac",
      "rating": 4,
      "user_ratings_total": 1279,
      "formatted_address": "Osječka ul. 29, 51000, Rijeka, Croatia",
      "coordinates": [
        14.427228,
        45.3374839
      ],
      "value_for_radius": 1279.0,
      "radius_km": 1.3528
    },
    "node/10793625756": {
      "name": "Plodine",
      "brand": "Studenac",
      "rating": 3.4,
      "user_ratings_total": 29,
      "formatted_address": "Zametska ul. 96A, 51000, Rijeka, Croatia",
      "coordinates": [
        14.3879901,
        45.3444995
      ],
      "value_for_radius": 29.0,
      "radius_km": 0.5
    },
    "node/11145771905": {
      "name": "Studenac Market",
      "brand": "",
      "rating": 3.8,
      "user_ratings_total": 39,
      "formatted_address": "Dvadesetdrugog lipnja 29, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4210016,
        45.3494978
      ],
      "value_for_radius": 39.0,
      "radius_km": 0.5
    },
    "node/11309376324": {
      "name": "SPAR supermarket Rijeka Čandekova",
      "brand": "Spar",
      "rating": 4,
      "user_ratings_total": 649,
      "formatted_address": "Ul. Franje Čandeka 8a, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4153995,
        45.3393062
      ],
      "value_for_radius": 649.0,
      "radius_km": 1.1596
    },
    "node/11338772769": {
      "name": "Studenac Market",
      "brand": "",
      "rating": 3.6,
      "user_ratings_total": 76,
      "formatted_address": "Trpimirova ul. 6, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4377229,
        45.32755
      ],
      "value_for_radius": 76.0,
      "radius_km": 0.5
    },
    "node/11434741150": {
      "name": "Plodine",
      "brand": "Plodine",
      "rating": 3.7,
      "user_ratings_total": 600,
      "formatted_address": "Ružićeva ul. 29, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4518441,
        45.3300497
      ],
      "value_for_radius": 600.0,
      "radius_km": 1.524
    },
    "node/11829811618": {
      "name": "Ultra",
      "brand": "",
      "rating": 3.9,
      "user_ratings_total": 67,
      "formatted_address": "Tizianova ul. 2, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4380661,
        45.3335836
      ],
      "value_for_radius": 67.0,
      "radius_km": 0.5
    },
    "node/11829955008": {
      "name": "Ultra",
      "brand": "",
      "rating": 3.9,
      "user_ratings_total": 67,
      "formatted_address": "Tizianova ul. 2, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4377734,
        45.3337629
      ],
      "value_for_radius": 67.0,
      "radius_km": 0.5
    },
    "node/11985614785": {
      "name": "Trgovina Šegota",
      "brand": "",
      "rating": 4,
      "user_ratings_total": 3,
      "formatted_address": "Mihanovićeva ul. 58, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4671115,
        45.3238056
      ],
      "value_for_radius": 3.0,
      "radius_km": 0.5
    },
    "node/11985614792": {
      "name": "Birota dućan",
      "brand": "",
      "rating": 4.1,
      "user_ratings_total": 22,
      "formatted_address": "Mihanovićeva ul. 21, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4632863,
        45.3240283
      ],
      "value_for_radius": 22.0,
      "radius_km": 0.5
    },
    "node/12073597246": {
      "name": "Konzum",
      "brand": "Konzum",
      "rating": 3.8,
      "user_ratings_total": 422,
      "formatted_address": "Ul. Nikole Tesle 9, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4310346,
        45.3320759
      ],
      "value_for_radius": 422.0,
      "radius_km": 0.9918
    },
    "node/12073605189": {
      "name": "Konzum",
      "brand": "Konzum",
      "rating": 3.9,
      "user_ratings_total": 1488,
      "formatted_address": "Osječka ul. 71, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4165101,
        45.3513573
      ],
      "value_for_radius": 1488.0,
      "radius_km": 1.668
    },
    "node/12085991804": {
      "name": "INTERSPAR hipermarket Rijeka Tower",
      "brand": "Spar",
      "rating": 4.2,
      "user_ratings_total": 2524,
      "formatted_address": "Janka Polića Kamova 81a, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4692893,
        45.3176729
      ],
      "value_for_radius": 2524.0,
      "radius_km": 2.2685
    },
    "node/12233204077": {
      "name": "Plodine Rijeka Drenova",
      "brand": "Plodine",
      "rating": 3.4,
      "user_ratings_total": 20,
      "formatted_address": "Ul. Ružice Mihić 20, 51000, Rijeka, Croatia",
      "coordinates": [
        14.426597,
        45.3563141
      ],
      "value_for_radius": 20.0,
      "radius_km": 0.5
    },
    "node/12328882581": {
      "name": "Smiljana",
      "brand": "Tommy",
      "rating": 4.3,
      "user_ratings_total": 114,
      "formatted_address": "Titov trg 12, 51000, Rijeka, Croatia",
      "coordinates": [
        14.4472545,
        45.327682
      ],
      "value_for_radius": 114.0,
      "radius_km": 0.5
    }
  },
  "description": "Generated HPO instance for stores whose formatted_address contains '51000, Rijeka'.",
  "id": "a66bd17c-5fa7-4650-81ad-cf70ad36095f",
  "run_info": {
    "status": "Not started",
    "updated_at": "2026-06-17T14:08:28.431862+00:00"
  },
  "settings": {
    "ga": {
      "crossover": {
        "params": {
          "children": [],
          "p": 1,
          "weights": [
            0.4,
            0.4,
            0.2
          ]
        },
        "type": "CompositeCrossover"
      },
      "deterministic": true,
      "eliminator": {
        "params": {
          "elitism": 5
        },
        "type": "EliteEliminator"
      },
      "fitness": {
        "params": {},
        "type": "FastIntersectUnionFitness"
      },
      "generations": 5000,
      "generator": {
        "params": {},
        "type": "AllSundaysHaveWorkGenerator"
      },
      "logger": {
        "params": {},
        "type": "SoutLogger"
      },
      "mutator": {
        "params": {
          "children": [],
          "p": 1,
          "weights": [
            1
          ]
        },
        "type": "CompositeMutator"
      },
      "newChromosomes": 2,
      "numThreads": 4,
      "populationSize": 100,
      "selection": {
        "params": {
          "tournamentSize": 3
        },
        "type": "TournamentSelection"
      },
      "stagnationFraction": 0.2,
      "timelimit": 300
    },
    "general": {
      "MAX_CLUSTER_DISTANCE": 3,
      "MAX_CLUSTER_JOIN_DISTANCE": 10
    }
  },
  "status": "initialized",
  "username": "jetpans",
  "value_calculator": null,
  "value_for_radius_calculator": "return store.get('user_ratings_total', 5) * 1"
}
